[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Aleph-Alpha/ts-rs"]
git = "https://github.com/Aleph-Alpha/ts-rs"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/run/build/ZooModelingApp/cargo/vendor"